Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "debian11-fw" do |v|
    v.vm.hostname = "debian11-fw"
    #v.vm.box_version = "11.20230501.1"
     v.vm.network :private_network, ip: "192.168.122.1",
      libvirt__network_name: "intnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8::4",
      libvirt__ipv6_prefix: "64"
      
    v.vm.network :private_network, ip: "192.168.124.1",
      libvirt__network_name: "extnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8:0:1::1",
      libvirt__ipv6_prefix: "64"
    
    v.vm.provision "shell", path:"prepare_victim.sh"
    
  end
end
