# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  #config.vm.provision "file", source: "Attacker_tool", destination: "."
  
  config.vm.define "ATTACKER" do |v|
    v.vm.hostname = "ATTACKER"
    
    v.vm.network :private_network, ip: "192.168.124.2",
      libvirt__network_name: "extnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8:0:1::3",
      libvirt__ipv6_prefix: "64"
    
    v.vm.provision "shell", path:"prepare_attacker.sh"
    
    v.vm.provision "shell", inline: <<-SCRIPT
sudo apt-get update
sudo apt install python3-pip
sudo apt install libnetfilter-queue-dev
sudo pip install NetfilterQueue
sudo apt install python3-scapy
SCRIPT
    
  end
  
end
