# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"
  config.vm.define "openbsd" do |v|
    v.vm.hostname = "openbsd"
  
    v.vm.network :private_network, ip: "192.168.122.1",
      libvirt__network_name: "intnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8::4",
      libvirt__ipv6_prefix: "64"
      
    v.vm.network :private_network, ip: "192.168.124.1",
      libvirt__network_name: "extnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8:0:1::1",
      libvirt__ipv6_prefix: "64"
      
    v.vm.provision "file", source: "hostname.vio2",     destination: "/tmp/hostname.vio2"
    v.vm.provision "file", source: "hostname.vio1",     destination: "/tmp/hostname.vio1"
    
    v.vm.provision "shell", inline: <<-SCRIPT
sudo cp /tmp/hostname.vio1 /etc/hostname.vio1
sudo cp /tmp/hostname.vio2 /etc/hostname.vio2
sudo sysctl -w net.inet6.ip6.forwarding=1
sudo sh /etc/netstart
SCRIPT
  
  end
end

