# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.define "archlinux" do |v|
  config.vm.synced_folder '.', '/vagrant', disabled: true
    v.vm.hostname = "archlinux"
    
    v.vm.network :private_network, ip: "192.168.122.2",
      libvirt__network_name: "intnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8::3",
      libvirt__ipv6_prefix: "64"
    
    v.vm.provision "shell", path: "./prepare_victim.sh"
    
  end
end
