# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2304"
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  
  config.vm.define "ubuntu23.04-machine" do |v|
    v.vm.hostname = "ubuntu23.04-machine"
    
     v.vm.network :private_network, ip: "192.168.122.2",
      libvirt__network_name: "intnet",
      libvirt__forward_mode: "veryisolated",
      libvirt__dhcp_enabled: false,
      libvirt__guest_ipv6: "yes",
      libvirt__ipv6_address: "2001:DB8::3",
      libvirt__ipv6_prefix: "64"
    
    v.vm.provision "shell", path:"prepare_victim.sh"
  end
end
